//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaFarHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FriendTagList
    {
        public int taggingID { get; set; }
        public int postID { get; set; }
        public string friendUsername { get; set; }
        public string friendUsernameWhoIsTagged { get; set; }
        public bool notificationSeen { get; set; }
        public bool clickedAndSeen { get; set; }
        public System.DateTime taggedDateTime { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual Picture Picture { get; set; }
    }
}
