//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaFarHub.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SaFarHubDatabaseEntities : DbContext
    {
        public SaFarHubDatabaseEntities()
            : base("name=SaFarHubDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FriendRequest> FriendRequests { get; set; }
        public virtual DbSet<FriendTagList> FriendTagLists { get; set; }
        public virtual DbSet<Picture> Pictures { get; set; }
        public virtual DbSet<PicturesComment> PicturesComments { get; set; }
        public virtual DbSet<PicturesLike> PicturesLikes { get; set; }
        public virtual DbSet<RecoveryReference> RecoveryReferences { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UsersFriend> UsersFriends { get; set; }
    }
}
