//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaFarHub.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Picture
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Picture()
        {
            this.FriendTagLists = new HashSet<FriendTagList>();
            this.PicturesComments = new HashSet<PicturesComment>();
            this.PicturesLikes = new HashSet<PicturesLike>();
        }
    
        public int pictureID { get; set; }
        public string username { get; set; }
        public string pictureAddress { get; set; }
        public string pictureCaption { get; set; }
        public Nullable<System.DateTime> uplaodDateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FriendTagList> FriendTagLists { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PicturesComment> PicturesComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PicturesLike> PicturesLikes { get; set; }


        public HttpPostedFileBase ImageFile { get; set; }
    }
}
